# version: '3.8'
# services:

#   app:
#     container_name: nestjs_boilerplate_app
#     #Dev mode
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: dev
#     command: ["pnpm", "start:dev"]
#     #Prod mode
#     # build:
#     #   context: .
#     #   dockerfile: Dockerfile
#     depends_on:
#       - db
#       - redis
#     env_file:
#       - .env
#     ports:
#       - $PORT:3000
#     networks:
#       - app_db
#       - app_redis

#   db:
#     container_name: nestjs_boilerplate_db
#     image: postgres:16-alpine
#     restart: always
#     environment:
#       POSTGRES_USER: $DB_USERNAME
#       POSTGRES_PASSWORD: $DB_PASSWORD
#       POSTGRES_DB: $DB_NAME
#     ports:
#       - $DB_HOST_PORT:$DB_PORT
#     volumes:
#       - .docker/db:/var/lib/postgresql
#     networks:
#       - app_db

#   redis:
#     container_name: nestjs_boilerplate_redis
#     image: redis:7-alpine
#     restart: always
#     command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
#     ports:
#       - $REDIS_HOST_PORT:$REDIS_PORT
#     volumes:
#       - .docker/redis:/data
#     networks:
#       - app_redis

# networks:
#   app_db:
#   app_redis:

version: '3.5'

services:
  # reactjs_client:
  #     build: client/test-app/.
  #     ports:
  #       - 3000:3000
  #     networks:
  #       custom_net:
  #         ipv4_address: 10.5.0.2

  # nodejs_server:
  #   build: server/.
  #   ports: 
  #     - 5001:5001
  #   networks:
  #     custom_net:
  #       ipv4_address: 10.5.0.3

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      custom_net:
        ipv4_address: 10.5.0.4
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - 5050:80
    networks:
      custom_net:
        ipv4_address: 10.5.0.5
    restart: unless-stopped

  redis:
    container_name: nestjs_boilerplate_redis
    image: redis:7-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    ports:
      - 6379:6379
    volumes:
      - .docker/redis:/data
    networks:
      custom_net:
        ipv4_address: 10.5.0.6

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
    postgres:
    pgadmin:
    nodejs_server: